"""empty message

Revision ID: 1e2d65e8637c
Revises: 592d13eb1e82
Create Date: 2019-05-29 17:54:13.715417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e2d65e8637c'
down_revision = '592d13eb1e82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin_power', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin_power')
    # ### end Alembic commands ###
