"""empty message

Revision ID: 592d13eb1e82
Revises: d75c17c173b2
Create Date: 2019-05-29 12:59:06.011974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592d13eb1e82'
down_revision = 'd75c17c173b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('postby')
    op.drop_table('ownship')
    op.drop_table('commenton')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commenton',
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.Column('comment', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], )
    )
    op.create_table('ownship',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('image_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['image.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('postby',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('comment_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###
