"""empty message

Revision ID: 94fb60acb6ef
Revises: 3de06828ae39
Create Date: 2019-05-28 10:57:54.443254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94fb60acb6ef'
down_revision = '3de06828ae39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'description')
    # ### end Alembic commands ###
