"""empty message

Revision ID: d75c17c173b2
Revises: 94fb60acb6ef
Create Date: 2019-05-28 16:22:25.094914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75c17c173b2'
down_revision = '94fb60acb6ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('image', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'created_at')
    op.drop_column('comment', 'created_at')
    # ### end Alembic commands ###
